### ISSUE TITLE
needs with initContainers and CNPG Clusters

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/kontinuous#359]
Looks like CNPG Cluster are not compatible with the init container mode

```
Cannot destructure property 'spec' of 'manifest.spec.template' as it is undefined.
TypeError: Cannot destructure property 'spec' of 'manifest.spec.template' as it is undefined.
    at module.exports (/private/var/folders/cj/ndwdv0lx5bq0hbbj6r5dbrf80000gn/T/kontinuous/build-zKrSqZ/charts/project/charts/fabrique/charts/contrib/patches/05.1-needs-using-initcontainers.js:49:13)
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/dist/index.js.cache.js:180413:30
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/webpack:/kontinuous/src/plugins/context/function.js:18:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/dist/index.js.cache.js:180413:24
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/webpack:/kontinuous/src/plugins/context/function.js:18:1
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/dist/index.js.cache.js:180413:24
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/webpack:/kontinuous/src/plugins/context/function.js:18:1
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/dist/index.js.cache.js:180413:24
    at /Users/julienb/.npm/_npx/6966c558fab4c17b/node_modules/kontinuous/webpack:/kontinuous/src/plugins/context/function.js:18:1
    ```

**Comment by devthejo** [comment]
caused by disabling the `needs` patch plugin (it should be enable), to test initContainers just use the extends `deploy-with-kubectl`, or more simple, because deploy plugin kubectl without dependencies tree not tested for a long time, enable the `needsUsinInitcontainers` plugin, build the manifests with kontinuous and apply the generated manifest using the kubectl cli (in case of limited right, possible you have to create the namespace first, due to rancher latency to allow perms on the ns)
